apiVersion: v1
kind: Service

metadata:
  name: search
  namespace: xkcd
  labels:
    app: search

spec:
  type: ClusterIP

  selector:
    app: search

  ports:
    - name: grpc
      protocol: TCP
      port: 8080
      targetPort: grpc
