{
 "title": "xkcd",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Statuses",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(sum(http_request_duration_seconds_count[$__rate_interval]) by (status))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "URL RPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "rate(sum(http_request_duration_seconds_count[$__rate_interval]) by (url))",
     "legendFormat": "{{url}}"
    }
   ]
  },
  {
   "title": "Latency, ms",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(sum(http_request_duration_seconds_sum[$__rate_interval]) by (url)) / rate(sum(http_request_duration_seconds_count[$__rate_interval]) by (url)) * 1000",
     "legendFormat": "{{url}}"
    }
   ]
  }
 ]
}